-- Testdaten für die Tabelle Projekt

INSERT INTO `projekt` (`ID`, `projekturl`, `projektname`, `projektbeschreibung`, `user_ID`) VALUES
(8, 'biznus.jpg', 'Kwideo Project', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 5),
(9, 'biznus.jpg', 'Brainlounge Webseite', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 3),
(10, 'biznus.jpg', 'Oyondu', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1),
(11, 'biznus.jpg', 'Oyonder', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 2),
(12, 'biznus.jpg', 'Zoovu Web & CI', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 3),
(13, 'biznus.jpg', 'Photofeed', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1),
(14, 'biznus.jpg', 'Yoveo Webseite', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1),
(15, 'biznus.jpg', 'Yombu.app', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2),
(16, 'biznus.jpg', 'Skinte', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1),
(17, 'biznus.jpg', 'Yodel', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 2),
(18, 'biznus.jpg', 'InnoZ', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 4),
(19, 'biznus.jpg', 'Topiclounge', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 3),
(20, 'biznus.jpg', 'Livetube', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 3),
(21, 'biznus.jpg', 'Quinu Test', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 5),
(22, 'biznus.jpg', 'Quire', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 4),
(23, 'biznus.jpg', 'Roombo AG', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3),
(24, 'biznus.jpg', 'Feedspan', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1),
(25, 'biznus.jpg', 'Rooxo App', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1),
(26, 'biznus.jpg', 'Skinder', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2),
(27, 'biznus.jpg', 'Ozu', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1),
(28, 'biznus.jpg', 'Talane', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 5),
(29, 'biznus.jpg', 'Wikivu', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 4),
(30, 'biznus.jpg', 'Eabox', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 4),
(31, 'biznus.jpg', 'Twitterbridge', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 4),
(32, 'biznus.jpg', 'ExCell AG Web', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 5);
